/**
 * GENERATED by scripts/build-hero-slides.ts. Do not edit.
 *
 * Run `npm run build:hero-slides` to regenerate. Each entry is one of the
 * store's wall murals in its 16:9 re-layout, with the wordmark already removed
 * at source: the hashed path under public/hero/, its intrinsic size, and a
 * 12x12 placeholder for the connection that will be a while getting the rest.
 *
 * The size is load bearing rather than informational. A phone pans across these
 * rather than holding a third of one, and the track that pans is sized from
 * this ratio (`.hero-pan-track` in app/globals.css).
 *
 * The order the hero plays these in is not here. See lib/hero/slideshow.ts.
 */

export type HeroImage = {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly blurDataURL: string;
};

export const HERO_IMAGES = {
  "eating": {
    src: "/hero/eating.b961f63a.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoMAAwAA4BaJaACdADxgIAA/qn0KTH7Fv2wYxPRIyvib7mJMlKUCvfRaCyUMqK0TJhl8KA86TnnD9dcFjW+IAAA",
  },
  "spread": {
    src: "/hero/spread.41f3da20.webp",
    width: 1672,
    height: 941,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAAwAA4BaJagCdH8AFcjCpAqYAP7zyIqs2129sg9YkTpnI50cmg8rdk/jdhHGr+tiJtjGZy9hdeHA6WLRmj8p3jdZjceI3zgAAA==",
  },
} as const satisfies Record<string, HeroImage>;

export type HeroImageName = keyof typeof HERO_IMAGES;
