/**
 * GENERATED by scripts/trace-mural.ts. Do not edit.
 *
 * Run `npm run build:mural` to regenerate. Each entry is a traced motif from
 * the store's wall artwork: the hashed path under public/mural/, and the
 * intrinsic size of its viewBox so a caller can reserve the right aspect ratio
 * without loading the file.
 */

export type MuralMotif = {
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

export const MURAL_MOTIFS = {
  "wall": { src: "/mural/wall.fcf7c432.svg", width: 2200, height: 1819 },
  "storefront": { src: "/mural/storefront.ca614dee.svg", width: 1600, height: 1187 },
  "storefront-small": { src: "/mural/storefront-small.a1c32c4c.svg", width: 1000, height: 742 },
  "signal": { src: "/mural/signal.27bdfc8d.svg", width: 1100, height: 990 },
  "tile-signal": { src: "/mural/tile-signal.2ae36db1.svg", width: 600, height: 635 },
  "tile-car": { src: "/mural/tile-car.ba5c4701.svg", width: 700, height: 420 },
  "tile-crowd": { src: "/mural/tile-crowd.f8ea73de.svg", width: 640, height: 673 },
  "skyline-band": { src: "/mural/skyline-band.ef4c128c.svg", width: 1560, height: 102 },
  "skyline": { src: "/mural/skyline.0a6cb78d.svg", width: 1100, height: 861 },
} as const satisfies Record<string, MuralMotif>;

export type MuralMotifName = keyof typeof MURAL_MOTIFS;
