import { writeFileSync } from "node:fs";
import { categories } from "../lib/catalog/menu";

const peso = (c: number) => (c / 100).toLocaleString("en-PH", { minimumFractionDigits: 2 });
const out: string[] = [];
const w = (l = "") => out.push(l);

w("# Menu prices to confirm");
w();
w("Generated by `npm run build:prices-to-confirm`. Do not edit by hand.");
w();
w("Every row below is on the NYBB menu and is switched **off** in this app,");
w("because the only price we have for it is Foodpanda's. Foodpanda prices carry");
w("that channel's markup, so they are not pickup prices. Each row needs one");
w("number from the owner, after which it is a price edit and a flip to active.");
w();
w("The Foodpanda column is `price_before_discount` from the SM City Cebu");
w("listing, captured 2026-09-07. A 15% vendor promo was masking the displayed");
w("`price` at the time, so the displayed figures were 15% lower than these.");
w();

let pending = 0;
for (const category of categories) {
  const off = category.items.filter((i) => i.active === false);
  if (off.length === 0) continue;
  w(`## ${category.name}`);
  w();
  w("| Item | Size | Foodpanda (delivery) | Pickup price |");
  w("| --- | --- | --- | --- |");
  for (const item of off) {
    pending += 1;
    for (const v of item.variations) {
      const size = item.variations.length === 1 ? "" : v.name;
      w(`| ${item.name} | ${size} | ${peso(v.priceCents)} | |`);
    }
  }
  w();
}

w("---");
w();
w("## Already on sale, but worth a second look");
w();
w("These are active, priced from our own list rather than from Foodpanda. The");
w("gaps are large enough that the source is probably out of date.");
w();
w("| Item | Ours | Foodpanda | Gap |");
w("| --- | --- | --- | --- |");
const spotChecks: [string, number, number][] = [
  ["Chicken Wings, half", 32900, 45800],
  ["Chicken Wings, full", 52900, 71900],
  ["Original Ribs", 34900, 45900],
  ["Chicken Nuggets, 6 pieces", 13100, 19500],
  ["Chicken Nuggets, 10 pieces", 21000, 28700],
  ["Rookie Burger", 15900, 13700],
  ["The Quarterback Burger", 22900, 24100],
  ["BLT Burger", 27900, 35600],
  ["Buffalo Chicken Burger", 30900, 33200],
  ["Classic Hotdog", 14900, 13300],
  ["Hungarian Sausage Sandwich", 23900, 24800],
  ["Spaghetti", 15600, 21400],
  ["Mozzarella Sticks", 29900, 41300],
  ["NY Fries", 12800, 10300],
  ["Iced Americano", 8900, 11900],
  ["Iced Vanilla", 13900, 16900],
  ["Level of Hotness, per level", 3000, 2900],
];
for (const [name, ours, fp] of spotChecks) {
  const delta = fp - ours;
  const pct = Math.round((delta / ours) * 100);
  w(`| ${name} | ${peso(ours)} | ${peso(fp)} | ${delta >= 0 ? "+" : ""}${pct}% |`);
}
w();
w(`**${pending} items are waiting on a price.**`);
w();
w("Open questions that are not a number:");
w();
w("- **NY Fries sizes.** We hold one price of 128. Foodpanda sells Small 103,");
w("  Medium 172 and Large 195. Which size is our 128, and do we sell all three?");
w("- **Hungarian With Rice.** We hold one price of 189. Foodpanda splits it into");
w("  Solo 213 and Meal 248.");
w("- **Value Meal Sets A, B and C.** Not on Foodpanda, which sells four named");
w("  value meals at 229 each. Did the sets survive?");
w("- **Waffles, Hawaiian BBQ and Chicken with Rice.** Kept on your instruction,");
w("  but they are not on the delivery menu. Confirm the counter still sells them.");
w("- **What's New.** Foodpanda carries an NY Umbrella at 349 and two Rainy Day");
w("  Rush 2026 bundles at 1299. Left out: one is merchandise rather than food,");
w("  and the bundles are seasonal, so seeding them into a permanent catalog");
w("  would go stale. Say the word and they go in.");
w("- **Option groups.** Foodpanda carries seven we do not model: Nuggets Sauce,");
w("  Extra Sauce (64 small / 156 large), Value Meal Sauce, Value Meal Fries");
w("  (+20 / +30), Choice of Drinks (+20 / +30) and two flavoured-fries pickers.");
w("  They only attach to items that are switched off, so they are not built yet.");
w();

writeFileSync("docs/MENU-PRICES-TO-CONFIRM.md", out.join("\n"), "utf8");
console.log(`docs/MENU-PRICES-TO-CONFIRM.md written, ${pending} items pending`);
